export const languages = [
    {
      name: "Javascript",
      desc: "JavaScript is a dynamic, high-level programming language primarily utilized for front-end web development. It enables interactive and dynamic features on websites, enhancing user experience.",
      link: "",
      img: "/logos/logo-javascript.svg",
    },
    {
      name: "Java",
      desc: "Java is a versatile, high-level programming language celebrated for its simplicity and readability. Widely used in web development, data science, and automation, Java's extensive libraries make it a go-to choice for various applications.",
      link: "",
      img: "/logos/java.png",
    },
    {
      name: "C++",
      desc: "C++ is a versatile programming language renowned for efficiency, commonly applied in system software, games, and performance-critical applications, supporting both procedural and object-oriented programming.",
      link: "",
      img: "/logos/c++.svg",
    },
    {
      name:"Kotlin",
      desc: "Kotlin is a modern programming language that runs on the Java Virtual Machine (JVM). It is designed to be fully interoperable with Java, offering concise syntax and enhanced safety features, making it a popular choice for Android app development.",
      link: "",
      img: "/logos/kotlin_icon_130893.png",
    },
    {
      name:"Typescript",
      desc: "TypeScript is a superset of JavaScript that adds static typing, enhancing code quality and maintainability. It enables developers to catch errors early and provides better tooling support, making it ideal for large-scale applications.",
      link: "",
      img: "/logos/ts.svg",
    }, 
  ];
  
  export const frontend = [
    {
      name: "Reactjs",
      desc: "React is an efficient JavaScript library for building user interfaces, known for its component-based architecture and seamless updates, simplifying the creation of interactive and scalable UIs.",
      link: "https://www.react.dev",
      img: "/logos/react-2.svg",
    },
    // {
    //   name: "Nextjs",
    //   desc: "React is an efficient JavaScript library for building user interfaces, known for its component-based architecture and seamless updates, simplifying the creation of interactive and scalable UIs.",
    //   link: "https://www.nextjs.org",
    //   img: "/logos/next-js-white.svg",
    // },
    {
      name: "Tailwind CSS",
      desc: "Tailwind CSS is a utility-first CSS framework that streamlines web development. By providing a set of pre-designed utility classes, Tailwind simplifies styling and allows for rapid and consistent UI development.",
      link: "https://www.nextjs.org",
      img: "/logos/tailwind-css-2.svg",
    },
    // {
    //   name: "Shadcn",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://ui.shadcn.com/",
    //   img: "/logos/shadcn.jpeg",
    // },
    {
      name: "Redux & RTK",
      desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
      link: "https://redux-toolkit.js.org/",
      img: "/logos/redux.svg",
    },
    {
      name:"Adriod",
      desc: "Android is a mobile operating system based on the Linux kernel, designed primarily for touchscreen devices. It supports a wide range of applications and is known for its flexibility and customization options.",
      link: "",
      img: "/logos/Andriod.png",
    }
    // {
    //   name: "Zustand",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://zustand-demo.pmnd.rs/",
    //   img: "/logos/zustand.svg",
    // },
    // {
    //   name: "React query",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://tanstack.com/query",
    //   img: "/logos/react-query.svg",
    // },
  ];
  
  // export const backend = [
  //   {
  //     name: "Springboot",
  //     desc: "Spring Boot is a Java-based framework that simplifies the development of production-ready applications. It offers built-in features like dependency injection, security, and data access, enabling rapid application development.",
  //     link: "",
  //     img: "/logos/spring.png",
  //   },
  //   // {
  //   //   name: "Expressjs",
  //   //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
  //   //   link: "https://expressjs.com/",
  //   //   img: "/logos/expressjs-109.svg",
  //   // },
  //   // {
  //   //   name: "Honojs",
  //   //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
  //   //   link: "https://expressjs.com/",
  //   //   img: "/logos/hono.svg",
  //   // },
  //   // {
  //   //   name: "Prisma",
  //   //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
  //   //   link: "https://expressjs.com/",
  //   //   img: "/logos/prisma-white.svg",
  //   // },
  //   // {
  //   //   name: "Postgresql",
  //   //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
  //   //   link: "https://expressjs.com/",
  //   //   img: "/logos/postgresql.svg",
  //   // },
  //   // {
  //   //   name: "MongoDB",
  //   //   desc: "MongoDB is a flexible NoSQL database, storing data in BSON documents for versatility. Its document-oriented approach and scalability make it ideal for diverse applications, simplifying development and handling large datasets efficiently.",
  //   //   link: "https://www.mongodb.com/",
  //   //   img: "/logos/mongodb-icon-2.svg",
  //   // },
  //   // {
  //   //   name: "Cloudflare Workers",
  //   //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
  //   //   link: "https://expressjs.com/",
  //   //   img: "/logos/cloudflare-workers.svg",
  //   // },
  // ];
  
  export const other = [
    {
      name: "AWS Ec2",
      desc: "Zod is a TypeScript-first schema declaration and validation library.",
      link: "https://aws.amazon.com/ec2/",
      img: "/logos/EC2.svg",
    },
    {
      name: "Aws S3",
      desc: "",
      link: "",
      img: "/logos/S3.png",
    },
    // {
    //   name: "Docker",
    //   desc: "Fast, disk space efficient package manager",
    //   link: "https://pnpm.io/",
    //   img: "/logos/docker.svg",
    // },
    // {
    //   name: "Turbo repo",
    //   desc: "Fast, disk space efficient package manager",
    //   link: "https://pnpm.io/",
    //   img: "/logos/turborepo.svg",
    // },
    // {
    //   name: "Ubuntu(Linux)",
    //   desc: "Ubuntu is a user-friendly Linux distribution recognized for its stability and security. It's widely used for desktop and server applications, featuring a customizable environment and extensive package support.",
    //   link: "https://ubuntu.com/",
    //   img: "/logos/ubuntu-4.svg",
    // },
  ];
  
  export const projects = [
    {
      name: "BMA Application",
      slug: "bma",
      desc: "BMA Application is a lead management application that I built as a part at Virtual Intelligence.",
      longDescription: "",
      liveLink: "",
      githubLink: "",
      coverImg: "/projects/bma.png",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "July 2024 - Present",
      tech: [
        "/logos/react-2.svg",
        "/logos/tailwind-css-2.svg",
        "/logos/shadcn.jpeg",
        "/logos/logo-javascript.svg",
      ],
    },
    {
      name: "My Portfolio",
      slug: "Protfolio",
      desc: "The website you are currently on.",
      longDescription: "",
      liveLink: "",
      githubLink: "",
      coverImg: "/projects/khushi.png",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "2025",
      tech: [
        "/logos/tailwind-css-2.svg",
        "/logos/react-2.svg",
      "/logos/logo-javascript.svg",
    ],
    },
    {
      name: "HR Console",
      slug: "hr-console",
      desc: "Developed employee and leave management modules with full CRUD operations and secure API integration. Implemented role-based access, automated notifications, and a user-friendly interface to streamline HR processes and improve operational efficiency",
      longDescription: "",
      liveLink: "https://play.google.com/store/apps/details?id=com.investmango.hrconsole&hl=en&pli=1",
      githubLink: "",
      coverImg: "/projects/HRconsole.jpeg",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "2024",
      tech: [
        "/logos/Andriod.png",
        "/logos/java.png",
      ]
    },
    {
      name: "Sanskar Mobile app",
      slug: "sanskartvapp",
      desc: "Developed OTT streaming applications for Android TV and mobile platforms. Integrated third-party playback SDKs, adaptive bitrate streaming, and social sharing features to deliver a seamless and responsive media experience across devices.",
      longDescription: "",
      liveLink: "https://play.google.com/store/apps/details?id=com.sanskar.tv&hl=en",
      githubLink: "",
      coverImg: "/projects/sanskartvapp.jpeg",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "2023s",
      tech: [
        "/logos/Andriod.png",
      "/logos/java.png",
      ]
    },
    // {
    //   name: "Healthsynx",
    //   slug: "healthsynx",
    //   desc: "HealthSynx is an innovative health and fitness tracker web application that empowers users to lead healthier lives. With clean and sleek design, goal setting, HealthSynx provides comprehensive insights and tracking capabilities.",
    //   longDescription: "",
    //   liveLink: "https://healthsynxx.vercel.app",
    //   githubLink: "https://github.com/adityaj07/healthsynx",
    //   coverImg: "/projects/project-healthsynx.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: [
    //     "/logos/react-2.svg",
    //     "/logos/tailwind-css-2.svg",
    //     "/logos/nodejs-1.svg",
    //     "/logos/expressjs-109.svg",
    //     "/logos/mongodb-icon-2.svg",
    //   ],
    // },
    // {
    //   name: "Databiz Landing Page",
    //   slug: "databiz-landing-page",
    //   desc: "dataBiz is a website landing page built with React and Tailwind Css. It also uses react-icons and react-typed libraries.",
    //   longDescription: "",
    //   liveLink: "https://databiz.netlify.app/",
    //   githubLink: "https://github.com/adityaj07/dataBiz",
    //   coverImg: "/projects/project-databiz.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: ["/logos/react-2.svg", "/logos/tailwind-css-2.svg"],
    // },
    // {
    //   name: "Ecolife",
    //   slug: "ecolife",
    //   desc: "EcoLife is a sustainable living website that I built as a project while learning Astro and as a part of my college project.",
    //   longDescription: "",
    //   liveLink: "https://ecoolife.netlify.app/",
    //   githubLink: "https://github.com/adityaj07/EcoLife",
    //   coverImg: "/projects/project-ecolife.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: ["/logos/astro.svg", "/logos/tailwind-css-2.svg"],
    // },
    // {
    //   name: "Lofiflow",
    //   slug: "lofiflow",
    //   desc: "LofiFlow is a webapp where you can listen to lofi music while you code.",
    //   longDescription: "",
    //   liveLink: "https://lofiflow.netlify.app/",
    //   githubLink: "",
    //   coverImg: "/projects/project-lofiflow.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: ["/logos/logo-javascript.svg", "/logos/tailwind-css-2.svg"],
    // },
    {
      name: "Working on more ideas.🤓",
      slug: "working-on-more-ideas",
      desc: "If you have any idea or want to get one built, reach out me.👀",
      longDescription: "",
      liveLink: "",
      githubLink: "",
      coverImg: "/projects/project-coming-soon.png",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "",
      tech: [],
    },
  ];
  
  export const experiences = [
    {
      title: "Software Engineer",
      company: "Bharuwa Solutions Pvt. Ltd",
      location: "Noida, India",
      duration: "Apr 2025 - Present",
      description:
        "Led design and development of cross-platform mobile apps using React Native with high-performance standards Collaborated with backend teams to integrate Node.js and GraphQL APIs for seamless mobile experience.Implemented CI/CD pipelines and automated testing to ensure fast and reliable delivery.Mentored junior developers, conducted peer reviews, and maintained code quality through linting and unit testing.Architected reusable components and scalable systems following modern software design principles",
      skills: [
        "React Native",
        "flutter",
        "githubAction",
        "Andriod Developer",
      ],
      logo: "/logos/engaze.svg",
    },{
      tittle:"Mobile App Developer (React Native)",
      company:"Invest Mango",
      location:"Noida , India",
      duration:"May 2024- Apr 2025",
      description:"Designed and built intuitive UI/UX for both Android and iOS platforms using React Native and Expo.Integrated RESTful APIs and Firebase for real-time data sync and authentication.Optimized performance using profiling tools and handled crash analytics for production builds.Collaborated in Agile teams, participating in sprint planning and client demos.",
      skills:["React Native", "Redux", "REST APIs", "Git", "Firebase", "Andriod"],
      logo: "/logos/engaze.svg",
    },
    {
      title:"Android Developer",
      company:"Sanskar Info Private Ltd",
      location:"Noida, India",
      duration:"Jan 2023 - May 2024",
      description:"Built native Android apps from scratch, following clean architecture and MVVM pattern.Integrated third-party SDKs for media playback, social sharing, and in-app messaging.Used Git for version control and handled builds and deployments via Android Studio.Engaged closely with UI/UX designers to bring wireframes into production-ready apps.",
      skills:[ "Java", "Kotlin", "Android Studio", "SQLite", "Firebase"],
      logo: "/logos/engaze.svg",
    }
  ];
  