export const languages = [
    {
      name: "Javascript",
      desc: "JavaScript is a dynamic, high-level programming language primarily utilized for front-end web development. It enables interactive and dynamic features on websites, enhancing user experience.",
      link: "",
      img: "/logos/logo-javascript.svg",
    },
    {
      name: "Java",
      desc: "Java is a versatile, high-level programming language celebrated for its simplicity and readability. Widely used in web development, data science, and automation, Java's extensive libraries make it a go-to choice for various applications.",
      link: "",
      img: "/logos/java.png",
    },
    {
      name: "C++",
      desc: "C++ is a versatile programming language renowned for efficiency, commonly applied in system software, games, and performance-critical applications, supporting both procedural and object-oriented programming.",
      link: "",
      img: "/logos/c++.svg",
    },
  ];
  
  export const frontend = [
    {
      name: "Reactjs",
      desc: "React is an efficient JavaScript library for building user interfaces, known for its component-based architecture and seamless updates, simplifying the creation of interactive and scalable UIs.",
      link: "https://www.react.dev",
      img: "/logos/react-2.svg",
    },
    // {
    //   name: "Nextjs",
    //   desc: "React is an efficient JavaScript library for building user interfaces, known for its component-based architecture and seamless updates, simplifying the creation of interactive and scalable UIs.",
    //   link: "https://www.nextjs.org",
    //   img: "/logos/next-js-white.svg",
    // },
    {
      name: "Tailwind CSS",
      desc: "Tailwind CSS is a utility-first CSS framework that streamlines web development. By providing a set of pre-designed utility classes, Tailwind simplifies styling and allows for rapid and consistent UI development.",
      link: "https://www.nextjs.org",
      img: "/logos/tailwind-css-2.svg",
    },
    {
      name: "Shadcn",
      desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
      link: "https://ui.shadcn.com/",
      img: "/logos/shadcn.jpeg",
    },
    {
      name: "Redux & RTK",
      desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
      link: "https://redux-toolkit.js.org/",
      img: "/logos/redux.svg",
    },
    // {
    //   name: "Zustand",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://zustand-demo.pmnd.rs/",
    //   img: "/logos/zustand.svg",
    // },
    // {
    //   name: "React query",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://tanstack.com/query",
    //   img: "/logos/react-query.svg",
    // },
  ];
  
  export const backend = [
    {
      name: "Springboot",
      desc: "Spring Boot is a Java-based framework that simplifies the development of production-ready applications. It offers built-in features like dependency injection, security, and data access, enabling rapid application development.",
      link: "",
      img: "/logos/spring.png",
    },
    // {
    //   name: "Expressjs",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://expressjs.com/",
    //   img: "/logos/expressjs-109.svg",
    // },
    // {
    //   name: "Honojs",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://expressjs.com/",
    //   img: "/logos/hono.svg",
    // },
    // {
    //   name: "Prisma",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://expressjs.com/",
    //   img: "/logos/prisma-white.svg",
    // },
    // {
    //   name: "Postgresql",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://expressjs.com/",
    //   img: "/logos/postgresql.svg",
    // },
    // {
    //   name: "MongoDB",
    //   desc: "MongoDB is a flexible NoSQL database, storing data in BSON documents for versatility. Its document-oriented approach and scalability make it ideal for diverse applications, simplifying development and handling large datasets efficiently.",
    //   link: "https://www.mongodb.com/",
    //   img: "/logos/mongodb-icon-2.svg",
    // },
    // {
    //   name: "Cloudflare Workers",
    //   desc: "Shadcn is a collection of re-usable components that you can copy and paste into your apps.",
    //   link: "https://expressjs.com/",
    //   img: "/logos/cloudflare-workers.svg",
    // },
  ];
  
  export const other = [
    {
      name: "AWS Ec2",
      desc: "Zod is a TypeScript-first schema declaration and validation library.",
      link: "https://aws.amazon.com/ec2/",
      img: "/logos/EC2.svg",
    },
    {
      name: "Aws S3",
      desc: "",
      link: "",
      img: "/logos/S3.png",
    },
    {
      name: "Docker",
      desc: "Fast, disk space efficient package manager",
      link: "https://pnpm.io/",
      img: "/logos/docker.svg",
    },
    // {
    //   name: "Turbo repo",
    //   desc: "Fast, disk space efficient package manager",
    //   link: "https://pnpm.io/",
    //   img: "/logos/turborepo.svg",
    // },
    // {
    //   name: "Ubuntu(Linux)",
    //   desc: "Ubuntu is a user-friendly Linux distribution recognized for its stability and security. It's widely used for desktop and server applications, featuring a customizable environment and extensive package support.",
    //   link: "https://ubuntu.com/",
    //   img: "/logos/ubuntu-4.svg",
    // },
  ];
  
  export const projects = [
    {
      name: "BMA Application",
      slug: "bma",
      desc: "BMA Application is a lead management application that I built as a part at Virtual Intelligence.",
      longDescription: "",
      liveLink: "",
      githubLink: "",
      coverImg: "/projects/bma.png",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "July 2024 - Present",
      tech: [
        "/logos/react-2.svg",
        "/logos/tailwind-css-2.svg",
        "/logos/shadcn.jpeg",
        "/logos/logo-javascript.svg",
      ],
    },
    {
      name: "My Portfolio",
      slug: "anushka",
      desc: "The website you are currently on.",
      longDescription: "",
      liveLink: "",
      githubLink: "",
      coverImg: "/projects/anushka.png",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "",
      tech: [
        "/logos/tailwind-css-2.svg",
        "/logos/react-2.svg",
      "/logos/logo-javascript.svg",
    ],
    },
    // {
    //   name: "Healthsynx",
    //   slug: "healthsynx",
    //   desc: "HealthSynx is an innovative health and fitness tracker web application that empowers users to lead healthier lives. With clean and sleek design, goal setting, HealthSynx provides comprehensive insights and tracking capabilities.",
    //   longDescription: "",
    //   liveLink: "https://healthsynxx.vercel.app",
    //   githubLink: "https://github.com/adityaj07/healthsynx",
    //   coverImg: "/projects/project-healthsynx.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: [
    //     "/logos/react-2.svg",
    //     "/logos/tailwind-css-2.svg",
    //     "/logos/nodejs-1.svg",
    //     "/logos/expressjs-109.svg",
    //     "/logos/mongodb-icon-2.svg",
    //   ],
    // },
    // {
    //   name: "Databiz Landing Page",
    //   slug: "databiz-landing-page",
    //   desc: "dataBiz is a website landing page built with React and Tailwind Css. It also uses react-icons and react-typed libraries.",
    //   longDescription: "",
    //   liveLink: "https://databiz.netlify.app/",
    //   githubLink: "https://github.com/adityaj07/dataBiz",
    //   coverImg: "/projects/project-databiz.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: ["/logos/react-2.svg", "/logos/tailwind-css-2.svg"],
    // },
    // {
    //   name: "Ecolife",
    //   slug: "ecolife",
    //   desc: "EcoLife is a sustainable living website that I built as a project while learning Astro and as a part of my college project.",
    //   longDescription: "",
    //   liveLink: "https://ecoolife.netlify.app/",
    //   githubLink: "https://github.com/adityaj07/EcoLife",
    //   coverImg: "/projects/project-ecolife.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: ["/logos/astro.svg", "/logos/tailwind-css-2.svg"],
    // },
    // {
    //   name: "Lofiflow",
    //   slug: "lofiflow",
    //   desc: "LofiFlow is a webapp where you can listen to lofi music while you code.",
    //   longDescription: "",
    //   liveLink: "https://lofiflow.netlify.app/",
    //   githubLink: "",
    //   coverImg: "/projects/project-lofiflow.png",
    //   imgs: [],
    //   screenshots: [],
    //   implementation: "",
    //   features: [],
    //   timeline: "",
    //   tech: ["/logos/logo-javascript.svg", "/logos/tailwind-css-2.svg"],
    // },
    {
      name: "Working on more ideas.🤓",
      slug: "working-on-more-ideas",
      desc: "If you have any idea or want to get one built, reach out me.👀",
      longDescription: "",
      liveLink: "",
      githubLink: "",
      coverImg: "/projects/project-coming-soon.png",
      imgs: [],
      screenshots: [],
      implementation: "",
      features: [],
      timeline: "",
      tech: [],
    },
  ];
  
  export const experiences = [
    {
      title: "Junior Software Development",
      company: "Virtual Intelligence",
      location: "Noida, India",
      duration: "May 2024 - Present",
      description:
        "At Virtual Intelligence, I worked as an Junior Software Development, juggling React.js, Tailwind, and  AWS Services to build and refine full-stack features. I contributed to the BMA Application , a lead Management application, and an admin panel, making things work (and work well). From crafting APIs to smoothing out UI/UX quirks, I wrote type-safe, scalable code while keeping performance snappy and architecture clean.",
      skills: [
        "React",
        "Tailwind CSS",
        "Shadcn",
        "Redux/RTK",
        "AWS Services(EC2, S3)",
      ],
      logo: "/logos/engaze.svg",
    },
  ];
  